# @package _global_

dataset_name: lerobot

dataset:
  _target_: diffusion_policy.dataset.dataloader_lerobot.UmiDatasetLeRobot
  shape_meta: ${task.shape_meta}
  dataset_path: data/umi_lerobot
  cache_dir: null
  action_padding: false
  temporally_independent_normalization: false
  max_duration: null
  normalizer_num_workers: 0
  seed: 42
  val_ratio: 0.05
  video_backend: pyav
