# @package _global_

defaults:
  - transformer_umi
  - override /task: umi_bimanual
  - _self_

dataset:
  dataset_path: data_workspace/fold_cloth/20231226_mirror_swap.zarr.zip

dataloader:
  batch_size: 24

val_dataloader:
  batch_size: 24

training:
  num_epochs: 100
