# @package _global_

defaults:
  - unet_timm_umi
  - override /task: umi_bimanual
  - override /augmentation: crop_rotate_color
  - _self_

dataset:
  dataset_path: data_workspace/fold_cloth/20231226_mirror_swap.zarr.zip

dataloader:
  batch_size: 32

val_dataloader:
  batch_size: 32

training:
  num_epochs: 100
  val_every: 5
